### ISSUE TITLE
How to share my location in the background?

### ISSUE THREAD

**Issue by jayisidoro** [piemonte/Position#2]
If I want to update my location in the background every 15 minutes for an hour, how would I do so with this library? Would I have my own NSTimer to end it and set the Position.sharedPosition.timeFilter to 15? 

EDIT:
How do I update location in the background? The documentation is a bit unclear on how to go about this process. Does oneshot imply only one attempt to update location? What method do I use to update location every time the user moves 40 meters? 

EDIT 2:
If I set a distance filter and a time filter, is the time filter to let the singleton know when it expires and the distance filter know when to update the user location?

**Comment by gizmosachin** [comment]
Hi @jayisidoro,
- `timeFilter` is not fully integrated yet, so you have two options
  - Set up your own timer and call the one shot method every 15 minutes manually
  - Call `startUpdating` to receive continuous background location updates and set `adjustLocationUseWhenBackgrounded` and `adjustLocationUseFromBatteryLevel` to minimize battery usage in the background

Re: Edit 1
- Background updates: make sure you've called `requestAlwaysAuthorization` and have set an `NSLocationAlwaysUsageDescription` to be able to get the user's location in the background. Then, call `startUpdating` to receive background location updates.
- The `performOneShotLocationUpdateWithDesiredAccuracy` method can be used to quickly get the user's current location with a desired accuracy (in meters). 

Re: Edit 2
- The `distanceFilter` property specifies the minimum distance (meters) that your device must move in order for `Position` to generate an update event, similar to how `CLLocationManager`'s `distanceFilter` works. Read more [here](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/distanceFilter). 
- In your case, to update location every time the user moves 40 meters, set `distanceFilter` = 40 and as long as you've called `startUpdating`, all observers will receive location updates every time your device moves >40 meters from the previously delivered location.

Hope this helps.
