### ISSUE TITLE
SwiftLocation vs Position

### ISSUE THREAD

**Issue by ugur10** [piemonte/Position#5]
Congrats Patrick, awesome work =)

What are the strengths over SwiftLocation? Why should I prefer one or the other? I need your wisdom.

**Comment by piemonte** [comment]
hey @ugur10 thanks much. ✌️  i'm not familiar with swiftlocation but i'm sure it's quite similar.

feel free to use whatever fits your requirements and isn't challenging to manage for yourself. swiftlocation looks like it has a larger following but also has to support a larger set of various features.
